### ISSUE TITLE
failed to req API:http://127.0.0.1:8848/nacos/v1/ns/api/clientBeat. code:500 msg: java.net.ConnectException:Connection refused

### ISSUE THREAD

**Issue by warlockhades** [alibaba/nacos#1617] opened 2019-07-28 02:59 UTC
原本想添加些详细内容的，结果换了namespace就可以注册了，以后有空了可能会补充详细信息

**Comment by chuntaojun** [comment] 2019-07-28 16:42
Duplicate of #1598

**Closed by chuntaojun** 2019-07-28 16:42 UTC
Labels: kind/bug
