### ISSUE TITLE
The parameter - Loader.path-Dloader.path of startup.sh is not valid

### ISSUE THREAD

**Issue by HuangRenhui** [alibaba/nacos#10816] opened 2023-07-19 02:02 UTC
i extend nacos-datasource-plugin for version 2.2.0 of nacos，the developed plugin jar is located in the decompressed directory of nacos server-1.1.4.tar.gz, under the directory of nacos/plugins/health，start startup.sh and discover that the data source implemented by the plugin is not valid
![1035493f512e32b3b3f205a0e4ed48e2](https://github.com/alibaba/nacos/assets/25076816/55d1e5d7-003a-495d-ac81-cc62d57d8fd7)
![81f2c7fd171353a7b3c4bfe2e0d76c0f](https://github.com/alibaba/nacos/assets/25076816/2ef5e58f-0bbd-4db0-8ccc-458337b784c6)
![3d039c6e0c2d797c3765b57f86d79b4b](https://github.com/alibaba/nacos/assets/25076816/716312cc-2aca-48e7-9cfb-4a5d97d786ef)
![4cd89805e4721cbc60561e08ffbec10c](https://github.com/alibaba/nacos/assets/25076816/c80cec74-b185-49eb-bd95-4f40491da499)

**Comment by KomachiSion** [comment] 2023-07-19 07:36
nacos server-1.1.4 is not support nacos-datasource-plugin

please upgrade to at least 2.2.0 and follow the document of nacos-datasource-plugin to add plugin.

**Comment by HuangRenhui** [comment] 2023-07-19 08:27
how to solve question:
Caused by: org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'db.pool.config' to com.zaxxer.hikari.HikariDataSource
        at org.springframework.boot.context.properties.bind.Binder.handleBindError(Binder.java:384)
        at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:344)
        at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:329)
        at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:259)
        at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:220)
        at com.alibaba.nacos.config.server.service.datasource.DataSourcePoolProperties.build(DataSourcePoolProperties.java:64)
        at com.alibaba.nacos.config.server.service.datasource.ExternalDataSourceProperties.build(ExternalDataSourceProperties.java:81)
        at com.alibaba.nacos.config.server.service.datasource.ExternalDataSourceServiceImpl.reload(ExternalDataSourceServiceImpl.java:134)
        ... 77 common frames omitted
Caused by: java.lang.IllegalStateException: Unable to set value for property driver-class-name

**Comment by HuangRenhui** [comment] 2023-07-19 08:30
i add db.pool.config.driverClassName=dm.jdbc.driver.DmDriver in application.properties or JAVA_OPT="${JAVA_OPT} -Ddb.pool.config.driverClassName=dm.jdbc.driver.DmDriver"  in startup.sh，but not valid

**Comment by HuangRenhui** [comment] 2023-07-20 02:13
> nacos server-1.1.4 is not support nacos-datasource-plugin
> 
> please upgrade to at least 2.2.0 and follow the document of nacos-datasource-plugin to add plugin.

----------------------------------------------------------------------------------

i upgrade version 2.2.0 of nacos,also i add db.pool.config.driverClassName=dm.jdbc.driver.DmDriver in application.properties or JAVA_OPT="${JAVA_OPT} -Ddb.pool.config.driverClassName=dm.jdbc.driver.DmDriver" in startup.sh，but not valid.
how to solve question:
Caused by: org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'db.pool.config' to com.zaxxer.hikari.HikariDataSource
at org.springframework.boot.context.properties.bind.Binder.handleBindError(Binder.java:384)
at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:344)
at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:329)
at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:259)
at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:220)
at com.alibaba.nacos.config.server.service.datasource.DataSourcePoolProperties.build(DataSourcePoolProperties.java:64)
at com.alibaba.nacos.config.server.service.datasource.ExternalDataSourceProperties.build(ExternalDataSourceProperties.java:81)
at com.alibaba.nacos.config.server.service.datasource.ExternalDataSourceServiceImpl.reload(ExternalDataSourceServiceImpl.java:134)
... 77 common frames omitted
Caused by: java.lang.IllegalStateException: Unable to set value for property driver-class-name

**Comment by KomachiSion** [comment] 2023-07-25 02:33
> > nacos server-1.1.4 is not support nacos-datasource-plugin
> > please upgrade to at least 2.2.0 and follow the document of nacos-datasource-plugin to add plugin.
> 
> i upgrade version 2.2.0 of nacos,also i add db.pool.config.driverClassName=dm.jdbc.driver.DmDriver in application.properties or JAVA_OPT="${JAVA_OPT} -Ddb.pool.config.driverClassName=dm.jdbc.driver.DmDriver" in startup.sh，but not valid. how to solve question: Caused by: org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'db.pool.config' to com.zaxxer.hikari.HikariDataSource at org.springframework.boot.context.properties.bind.Binder.handleBindError(Binder.java:384) at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:344) at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:329) at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:259) at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:220) at com.alibaba.nacos.config.server.service.datasource.DataSourcePoolProperties.build(DataSourcePoolProperties.java:64) at com.alibaba.nacos.config.server.service.datasource.ExternalDataSourceProperties.build(ExternalDataSourceProperties.java:81) at com.alibaba.nacos.config.server.service.datasource.ExternalDataSourceServiceImpl.reload(ExternalDataSourceServiceImpl.java:134) ... 77 common frames omitted Caused by: java.lang.IllegalStateException: Unable to set value for property driver-class-name

I saw the new issue #10833, should we merge these two issue as once?

Or close this issue and move to #10833 to discuss the new issue?

**Comment by HuangRenhui** [comment] 2023-07-26 02:38
> > > nacos server-1.1.4 is not support nacos-datasource-plugin
> > > please upgrade to at least 2.2.0 and follow the document of nacos-datasource-plugin to add plugin.
> > 
> > 
> > i upgrade version 2.2.0 of nacos,also i add db.pool.config.driverClassName=dm.jdbc.driver.DmDriver in application.properties or JAVA_OPT="${JAVA_OPT} -Ddb.pool.config.driverClassName=dm.jdbc.driver.DmDriver" in startup.sh，but not valid. how to solve question: Caused by: org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'db.pool.config' to com.zaxxer.hikari.HikariDataSource at org.springframework.boot.context.properties.bind.Binder.handleBindError(Binder.java:384) at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:344) at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:329) at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:259) at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:220) at com.alibaba.nacos.config.server.service.datasource.DataSourcePoolProperties.build(DataSourcePoolProperties.java:64) at com.alibaba.nacos.config.server.service.datasource.ExternalDataSourceProperties.build(ExternalDataSourceProperties.java:81) at com.alibaba.nacos.config.server.service.datasource.ExternalDataSourceServiceImpl.reload(ExternalDataSourceServiceImpl.java:134) ... 77 common frames omitted Caused by: java.lang.IllegalStateException: Unable to set value for property driver-class-name
> 
> I saw the new issue #10833, should we merge these two issue as once?
> 
> Or close this issue and move to #10833 to discuss the new issue?

i had close issue #10833

**Comment by KomachiSion** [comment] 2023-11-20 06:01
From my test, the properties is can be set to HikariDatasource, you set failed maybe caused by you do not depend the `dm.jdbc.driver.DmDriver` into the classpath.

The full stack like 

```
Caused by: java.lang.RuntimeException: org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'db.pool.config' to com.zaxxer.hikari.HikariDataSource
	at com.alibaba.nacos.persistence.datasource.DynamicDataSource.getDataSource(DynamicDataSource.java:60)
	at com.alibaba.nacos.persistence.repository.embedded.operate.StandaloneDatabaseOperateImpl.init(StandaloneDatabaseOperateImpl.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
	... 119 common frames omitted
Caused by: org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'db.pool.config' to com.zaxxer.hikari.HikariDataSource
	at org.springframework.boot.context.properties.bind.Binder.handleBindError(Binder.java:387)
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:347)
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:332)
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:262)
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:223)
	at com.alibaba.nacos.persistence.datasource.DataSourcePoolProperties.build(DataSourcePoolProperties.java:64)
	at com.alibaba.nacos.persistence.datasource.LocalDataSourceServiceImpl.initialize(LocalDataSourceServiceImpl.java:150)
	at com.alibaba.nacos.persistence.datasource.LocalDataSourceServiceImpl.init(LocalDataSourceServiceImpl.java:86)
	at com.alibaba.nacos.persistence.datasource.DynamicDataSource.getDataSource(DynamicDataSource.java:49)
	... 127 common frames omitted
Caused by: java.lang.IllegalStateException: Unable to set value for property driver-class-name
	at org.springframework.boot.context.properties.bind.JavaBeanBinder$BeanProperty.setValue(JavaBeanBinder.java:375)
	at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:104)
	at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:86)
	at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:62)
	at org.springframework.boot.context.properties.bind.Binder.lambda$bindDataObject$5(Binder.java:476)
	at org.springframework.boot.context.properties.bind.Binder$Context.withIncreasedDepth(Binder.java:590)
	at org.springframework.boot.context.properties.bind.Binder$Context.withDataObject(Binder.java:576)
	at org.springframework.boot.context.properties.bind.Binder$Context.access$300(Binder.java:537)
	at org.springframework.boot.context.properties.bind.Binder.bindDataObject(Binder.java:474)
	at org.springframework.boot.context.properties.bind.Binder.bindObject(Binder.java:414)
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:343)
	... 134 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.context.properties.bind.JavaBeanBinder$BeanProperty.setValue(JavaBeanBinder.java:372)
	... 144 common frames omitted
Caused by: java.lang.RuntimeException: Failed to load driver class dm.jdbc.driver.DmDriver in either of HikariConfig class loader or Thread context classloader
	at com.zaxxer.hikari.HikariConfig.setDriverClassName(HikariConfig.java:485)
	... 149 common frames omitted
```

The root reason is hikari datasource can't load  `dm.jdbc.driver.DmDriver`

**Closed** 2023-11-28 07:24 UTC
Labels: status/need feedback, plugin
