### ISSUE TITLE
Nacos service instance list inconsistent across the cluster

### ISSUE THREAD

**Issue by FinalVersion** [alibaba/nacos#6018] opened 2021-06-09 04:07 UTC
**Describe the bug**
One of the nacos servers returns out-of-date instance list for a few services, while the other nacos servers in the cluster return the correct instance list.

**Expected behavior**
All the servers should return the same instance list (eventually) for any service

**How to Reproduce**
Unknown

**Desktop (please complete the following information):**
 - OS: Centos 7
 - Version: nacos-server 1.1.4
 - Module: naming

**Additional context**
naming-distro.log produces logs like below:
```
2021-06-04 15:32:51,353 INFO creating service com.alibaba.nacos.naming.iplist.ephemeral.21c7187d-c748-4fc9-916e-0c270f0509ee##unknown@@_removing_sensitive_data_

2021-06-04 15:33:01,173 INFO creating service com.alibaba.nacos.naming.iplist.ephemeral.21c7187d-c748-4fc9-916e-0c270f0509ee##unknown@@_removing_sensitive_data_

2021-06-04 15:33:20,509 INFO creating service com.alibaba.nacos.naming.iplist.ephemeral.21c7187d-c748-4fc9-916e-0c270f0509ee##unknown@@_removing_sensitive_data_

2021-06-04 15:33:20,562 INFO creating service com.alibaba.nacos.naming.iplist.ephemeral.21c7187d-c748-4fc9-916e-0c270f0509ee##unknown@@_removing_sensitive_data_

2021-06-04 15:33:20,845 WARN sync checksum task already in process with 10.62.248.208:8848

2021-06-04 15:33:25,891 WARN sync checksum task already in process with 10.62.248.208:8848

2021-06-04 15:33:30,955 WARN sync checksum task already in process with 10.62.248.208:8848

2021-06-04 15:33:35,999 WARN sync checksum task already in process with 10.62.248.208:8848

2021-06-04 15:33:41,038 WARN sync checksum task already in process with 10.62.248.208:8848
```

It looks like the same issue as [#3708](https://github.com/alibaba/nacos/issues/3708)

The metrics shows some exceptional event happend around 06-04 15:33

![image](https://user-images.githubusercontent.com/4286873/121291274-91f4bc00-c91a-11eb-9b51-e82e244f7b54.png)
![nacos](https://user-images.githubusercontent.com/4286873/121291631-2c54ff80-c91b-11eb-9afb-47f0b18598b3.png)

**Comment by KomachiSion** [comment] 2021-06-09 06:53
1.1.4 is too old, please upgrade to new version and retry.

**Comment by FinalVersion** [comment] 2021-06-09 07:44
Haven't been able to reproduce it, hence not able to retry on newer versions. 
If there's already a fix, could you share the PR link?

**Comment by KomachiSion** [comment] 2021-06-10 01:41
I don't know what's your problem actually, so I can't get the PR about this problem. Please upgrade to newest version. 
If already fix and can't reproduce. Please ignore it.

**Comment by FinalVersion** [comment] 2021-06-10 03:44
> I don't know what's your problem actually
To be more specific, our nacos cluster consists of 8 servers, namely N1...N8. N1 returns 8 unhealthy instances (which have already been shutdown and shouldn't be in the instance list) for service X, while N2...N8 returns 11 healthy instances for service X. It is expected for N1 to return 11 healthy instances.

This bug can lead to severe HA and QoS issue for service X, so we need to thoroughly investigate and ensure it's fixed in future nacos versions

**Comment by KomachiSion** [comment] 2021-06-15 03:58
I will be fixed completely in 2.X version, because nacos change the way for syncing data.

In 1.X version, It seems only happen in some special envs. So I suggest you upgrade to 1.4.2 or 2.0.2 and retry.

**Comment by FinalVersion** [comment] 2021-06-20 11:11
> It will be fixed completely in 2.X version, because nacos change the way for syncing data.
> 
> In 1.X version, It seems only happen in some special envs. So I suggest you upgrade to 1.4.2 or 2.0.2 and retry.

I see. Will try with 2.x version later.

**Comment by KomachiSion** [comment] 2021-06-28 01:27
If reproduce this problem, please keep the logs and try to research why checksum task is not finished.

**Closed by KomachiSion** 2021-06-28 01:27 UTC
Labels: status/need feedback
