### ISSUE TITLE
[Enhancement] Adding the destroy lifecycle method on NamingMaintainService

### ISSUE THREAD

**Issue by mercyblitz** [alibaba/nacos#3576] opened 2020-08-11 08:32 UTC

**Comment by KomachiSion** [comment] 2020-08-11 08:45
Hi @mercyblitz , please edit your issue description with template. Thanks.



**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
A clear and concise description of what you want to happen.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
Add any other context or screenshots about the feature request here.

**Comment by zongtanghu** [comment] 2020-08-11 08:48
This issue can be assigned to me, firstly!I will resolve it. @KomachiSion @mercyblitz

**Comment by KomachiSion** [comment] 2020-10-13 06:03
@zongtanghu No response and process from you for a long time, I unassigned you.

**Comment by JackSun-Developer** [comment] 2020-10-13 06:11
@I will solve it@

**Closed** 2020-10-14 02:17 UTC
Labels: contribution welcome, kind/enhancement
