### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by kathetina** [alibaba/nacos#1364] opened 2019-06-13 03:26 UTC
1. dubbo-2.7.2 + dubbo-registry-nacos-2.7.2+nacos-1.0.1
2. error message
Exception in thread "main" java.lang.NoClassDefFoundError: com/alibaba/nacos/client/naming/utils/StringUtils
        at org.apache.dubbo.registry.nacos.NacosRegistryFactory.putPropertyIfAbsent(NacosRegistryFactory.java:104)
        at org.apache.dubbo.registry.nacos.NacosRegistryFactory.setProperties(NacosRegistryFactory.java:94)
        at org.apache.dubbo.registry.nacos.NacosRegistryFactory.buildNacosProperties(NacosRegistryFactory.java:73)
        at org.apache.dubbo.registry.nacos.NacosRegistryFactory.buildNamingService(NacosRegistryFactory.java:57)
        at org.apache.dubbo.registry.nacos.NacosRegistryFactory.createRegistry(NacosRegistryFactory.java:53)
        at org.apache.dubbo.registry.support.AbstractRegistryFactory.getRegistry(AbstractRegistryFactory.java:103)
        at org.apache.dubbo.registry.RegistryFactory$Adaptive.getRegistry(RegistryFactory$Adaptive.java)
        at org.apache.dubbo.registry.integration.RegistryProtocol.getRegistry(RegistryProtocol.java:298)
        at org.apache.dubbo.registry.integration.RegistryProtocol.export(RegistryProtocol.java:212)
        at org.apache.dubbo.qos.protocol.QosProtocolWrapper.export(QosProtocolWrapper.java:61)
        at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper.export(ProtocolFilterWrapper.java:120)
        at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.export(ProtocolListenerWrapper.java:59)
        at org.apache.dubbo.rpc.Protocol$Adaptive.export(Protocol$Adaptive.java)
        at org.apache.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:607)
        at org.apache.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:457)
        at org.apache.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:415)
        at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:378)
        at org.apache.dubbo.config.spring.ServiceBean.export(ServiceBean.java:336)
        at org.apache.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:114)
        at org.apache.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:60)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347)
        at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:883)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)
        at org.apache.dubbo.container.spring.SpringContainer.start(SpringContainer.java:50)
        at org.apache.dubbo.container.Main.main(Main.java:90)
Caused by: java.lang.ClassNotFoundException: com.alibaba.nacos.client.naming.utils.StringUtils
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

3. 

there is no StringUtils:
<img width="1101" alt="image" src="https://user-images.githubusercontent.com/8829397/59401600-d69df900-8dcd-11e9-8c31-1ecedd8bf7aa.png">

there is StringUtils:
<img width="1073" alt="image" src="https://user-images.githubusercontent.com/8829397/59401620-e9b0c900-8dcd-11e9-8af0-52142c0bd5d7.png">

**Comment by nkorange** [comment] 2019-06-13 06:10
The cause of this error is that ```com.alibaba.nacos.client.naming.utils.StringUtils``` is moved to  ```com.alibaba.nacos.client.utils.StringUtils```. Currently you have to fall back to Nacos 1.0.0. Report this bug to Dubbo please, they should change their invocation of StringUtils.

**Comment by nkorange** [comment] 2019-06-14 08:45
This problem will be fixed in the next version of Dubbo.

**Closed by nkorange** 2019-06-14 08:45 UTC
Labels: area/Dubbo, kind/bug

**Comment by moayi** [comment] 2019-11-06 16:43
你好，我在整合spingmvc和nacos,能提供        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>dubbo-registry-nacos</artifactId>
            <version>0.0.2</version>
        </dependency>
        
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>dubbo</artifactId>
            <version>2.6.5</version>
        </dependency>
        
        <dependency>
            <groupId>com.alibaba.spring</groupId>
            <artifactId>spring-context-support</artifactId>
            <version>1.0.2</version>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-all</artifactId>
            <version>4.1.22.Final</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>fastjson</artifactId>
            <version>${fastjson.version}</version>
        </dependency>
        
        <dependency>
            <groupId>com.alibaba.nacos</groupId>
            <artifactId>nacos-spring-context</artifactId>
            <version>0.3.3</version>
        </dependency>
        
        <dependency>
            <groupId>com.alibaba.nacos</groupId>
            <artifactId>nacos-client</artifactId>
            <version>1.1.4</version>
        </dependency>
的版本对吗？
