### ISSUE TITLE
`IPUtil` can't match localhost

### ISSUE THREAD

**Issue by haoyann** [alibaba/nacos#5765] opened 2021-05-18 03:46 UTC
**Describe the bug**
`serverAddr` use `localhost:8848` then `IPUtil` can't match.
![image](https://user-images.githubusercontent.com/43994656/118587007-5b6dca80-b7ce-11eb-9cf8-7ac529f5b7eb.png)

**Desktop (please complete the following information):**
 - Version develop
 - Module [naming/config]
 - SDK [java]

**Additional context**
```
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_271]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_271]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_271]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_271]
	at com.alibaba.nacos.api.config.ConfigFactory.createConfigService(ConfigFactory.java:43) ~[nacos-api-2.0.2-SNAPSHOT.jar:na]
	... 45 common frames omitted
Caused by: java.lang.IllegalArgumentException: The IPv4 or Domain address("localhost") is incorrect.
	at com.alibaba.nacos.common.utils.IPUtil.splitIPPortStr(IPUtil.java:138) ~[nacos-common-2.0.2-SNAPSHOT.jar:na]
	at com.alibaba.nacos.client.config.impl.ServerListManager.<init>(ServerListManager.java:162) ~[nacos-client-2.0.2-SNAPSHOT.jar:na]
	at com.alibaba.nacos.client.config.NacosConfigService.<init>(NacosConfigService.java:74) ~[nacos-client-2.0.2-SNAPSHOT.jar:na]
	... 50 common frames omitted
```

**Comment by JackSun-Developer** [comment] 2021-05-18 06:09
This problem can be reproduced stably.

**Comment by MentosL** [comment] 2021-05-18 08:58
@JackSun-Developer   @haoyann   The Develop branch has been changed and should work properly。

![image](https://user-images.githubusercontent.com/33775732/118622757-31ca9880-b7fa-11eb-9490-f3b42b041299.png)

**Comment by KomachiSion** [comment] 2021-05-19 09:40
https://github.com/alibaba/nacos/pull/5514 This PR caused

**Comment by SunJiFengPlus** [comment] 2021-05-19 09:56
i can do this, please assign to me

**Comment by KomachiSion** [comment] 2021-05-25 06:17
This issue is not solve completely

Caused by: java.lang.IllegalArgumentException: The IPv4 or Domain address("localhost") is incorrect.
        at com.alibaba.nacos.common.utils.IPUtil.splitIPPortStr(IPUtil.java:138)
        at com.alibaba.nacos.core.cluster.MemberUtil.singleParse(MemberUtil.java:76)
        at com.alibaba.nacos.core.cluster.ServerMemberManager.init(ServerMemberManager.java:139)
        at com.alibaba.nacos.core.cluster.ServerMemberManager.<init>(ServerMemberManager.java:132)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:175)
        ... 118 common frames omitted

**Closed** 2021-05-27 11:01 UTC
Labels: kind/bug
