### ISSUE TITLE
How to make prometheus automatically monitor nacos client?

### ISSUE THREAD

**Issue by shy000000** [alibaba/nacos#3052] opened 2020-06-12 09:00 UTC
When an application is packaged as a docker image and deployed using K8S,the ip of pod is frequently changed.
I wonder if there is a better way for prometheus to read the list of nacos server and automatically monitor the applications registered on it.

**Comment by KomachiSion** [comment] 2020-06-12 12:47
I think this issue is not nacos issue?

I can provide some advice for you: use pod name replace ip to monitor may solve your problem.

BTW, I will close this issue, because the issue is not nacos' issue. You more likely to get accurate answers from K8S communities.

**Closed by KomachiSion** 2020-06-12 12:47 UTC
