### ISSUE TITLE
[Enhancement] The unnecessary longpoll thead is maked in Clientworker

### ISSUE THREAD

**Issue by brotherlu-xcq** [alibaba/nacos#5534] opened 2021-04-29 08:45 UTC
**Describe the bug**
The executorService in Clientworker always inited with corePoolSize = runtimeProcesser as below.
when our Cachedata is less than the corePoolSize, the most of the thread will not be used and always in waiting status.
![image](https://user-images.githubusercontent.com/25661357/116524024-79e85080-a909-11eb-89e9-e4f6d489d4c1.png)

**Expected behavior**
I think we can juge the corePoolSize by our cacheData and runtimeProcesser to choose a reasonable size.

**Acutally behavior**
always equals runtimeProcesser.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [1.x lasted ]
 - Module [client]

**Additional context**
no

**Comment by shiyiyue1102** [comment] 2021-07-07 02:47
You may have a misunderstanding of 'corePoolSize'，no thread will be created if no task be submited.

**Comment by shiyiyue1102** [comment] 2021-07-13 06:09
Not reply for a long time , and this seems not a bug, close this issue

**Closed by shiyiyue1102** 2021-07-13 06:09 UTC
Labels: area/Config
