### ISSUE TITLE
nacos 微服务运行一段时间宕机

### ISSUE THREAD

**Issue by Johor03** [alibaba/nacos#7396] opened 2021-12-11 03:42 UTC
服务在k8s上运行，配置中心，注册中心使用nacos, 
nacos-server 2.0.3集群
nacos-client 2.0.3
![Uploading image.png…]()

宕机前日志

2021-12-11 11:17:21,785  WARN 1 TID:N/A [       Thread-5] c.a.n.common.http.HttpClientBeanHolder   : [HttpClientBeanHolder] Start destroying common HttpClient
2021-12-11 11:17:21,787  INFO 1 TID:N/A [      Thread-30] c.n.l.PollingServerListUpdater           : Shutting down the Executor Pool for PollingServerListUpdater
2021-12-11 11:17:21,787  WARN 1 TID:N/A [      Thread-12] c.a.nacos.common.notify.NotifyCenter     : [NotifyCenter] Start destroying Publisher
2021-12-11 11:17:21,787  WARN 1 TID:N/A [      Thread-12] c.a.nacos.common.notify.NotifyCenter     : [NotifyCenter] Destruction of the end
2021-12-11 11:17:21,794  WARN 1 TID:N/A [       Thread-5] c.a.n.common.http.HttpClientBeanHolder   : [HttpClientBeanHolder] Destruction of the end
2021-12-11 11:17:21,963  INFO 1 TID:N/A [extShutdownHook] o.s.s.c.ThreadPoolTaskScheduler          : Shutting down ExecutorService 'Nacos-Watch-Task-Scheduler'
2021-12-11 11:17:21,999  INFO 1 TID:N/A [extShutdownHook] c.a.c.n.registry.NacosServiceRegistry    : De-registering from Nacos Server now...
2021-12-11 11:17:22,002  INFO 1 TID:N/A [extShutdownHook] c.a.c.n.registry.NacosServiceRegistry    : De-registration finished.
2021-12-11 11:17:22,315  INFO 1 TID:N/A [extShutdownHook] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'taskExecutor'

**Comment by Johor03** [comment] 2021-12-11 03:42
![image](https://user-images.githubusercontent.com/15308362/145662540-647dc023-bcbf-4424-9a7c-808b493ca360.png)

**Comment by SteafanMrZhou** [comment] 2021-12-13 03:08
看了下你的宕机前日志，应该是你的服务在运行过程中发生了某种异常，导致 Nacos 从 Common 模块开始 Shutdown 了你的服务线程，能否提供下服务监控日志，或者服务发生宕机的日志。

**Comment by luguoqi** [comment] 2022-03-21 11:54
扒了下源码，在NacosDiscoveryProperties初始化或者变更的时候会发一个事件，后续监听的事件里会stop掉客户端，再start，但只有一次，配置变更时再次新建NacosDiscoveryProperties，继续走上述流程时，就只会走stop，不会走start，导致客户端被stop掉之后没有在start，所以接着服务也被关掉了，不知道是不是这样。
![image](https://user-images.githubusercontent.com/24733117/159256064-c97fb097-1ccb-4e37-979f-335e470a2240.png)

**Comment by jjh000gx** [comment] 2022-05-24 05:27
> 看了下你的宕机前日志，应该是你的服务在运行过程中发生了某种异常，导致 Nacos 从 Common 模块开始 Shutdown 了你的服务线程，能否提供下服务监控日志，或者服务发生宕机的日志。
我的服务器端版本是 2.1.0， nacos client 是 2.0.3

2022-05-23 18:16:57,402 [com.alibaba.nacos.client.naming.updater.2] ERROR [com.alibaba.nacos.common.remote.client] [LoggerUtils.java:99] [trace=,span=,parent=] - Send request fail, request=ServiceQueryRequest{headers={}, requestId='null'}, retryTimes=1,errorMessage=Client not connected,current status:UNHEALTHY
2022-05-23 18:16:57,402 [com.alibaba.nacos.client.Worker] ERROR [com.alibaba.nacos.common.remote.client] [LoggerUtils.java:99] [trace=,span=,parent=] - Send request fail, request=ConfigBatchListenRequest{headers={}, requestId='null'}, retryTimes=1,errorMessage=Client not connected,current status:UNHEALTHY
2022-05-23 18:16:57,450 [com.alibaba.nacos.client.remote.worker] INFO  [com.alibaba.nacos.common.remote.client] [LoggerUtils.java:60] [trace=,span=,parent=] - [e3148ab7-3a66-42db-bd7e-8b515f1250b4_config-0] success to connect a server  [172.18.87.174:8848],connectionId=1653301017320_172.18.86.63_51988
2022-05-23 18:16:57,451 [com.alibaba.nacos.client.remote.worker] INFO  [com.alibaba.nacos.common.remote.client] [LoggerUtils.java:60] [trace=,span=,parent=] - [e3148ab7-3a66-42db-bd7e-8b515f1250b4_config-0] Abandon prev connection ,server is  172.18.87.174:8848, connectionId is 1653292492450_172.18.86.63_45132
2022-05-23 18:16:57,453 [com.alibaba.nacos.client.remote.worker] INFO  [com.alibaba.nacos.common.remote.client] [LoggerUtils.java:60] [trace=,span=,parent=] - [efaccc35-ff65-47c5-ab6b-ecdc60b1932d] success to connect a server  [119.23.204.229:8848],connectionId=1653301017331_119.23.204.229_41692
2022-05-23 18:16:57,453 [com.alibaba.nacos.client.remote.worker] INFO  [com.alibaba.nacos.common.remote.client] [LoggerUtils.java:60] [trace=,span=,parent=] - [efaccc35-ff65-47c5-ab6b-ecdc60b1932d] Abandon prev connection ,server is  119.23.204.229:8848, connectionId is 1653292504362_119.23.204.229_34954
2022-05-23 18:16:57,455 [com.alibaba.nacos.client.remote.worker] INFO  [com.alibaba.nacos.common.remote.client] [LoggerUtils.java:60] [trace=,span=,parent=] - [e3148ab7-3a66-42db-bd7e-8b515f1250b4_config-0] try to re connect to a new server ,server is  not appointed,will choose a random server.
2022-05-23 18:16:57,455 [com.alibaba.nacos.client.remote.worker] INFO  [com.alibaba.nacos.common.remote.client] [LoggerUtils.java:60] [trace=,span=,parent=] - [efaccc35-ff65-47c5-ab6b-ecdc60b1932d] try to re connect to a new server ,server is  not appointed,will choose a random server.
2022-05-23 18:16:57,455 [com.alibaba.nacos.client.remote.worker] INFO  [com.alibaba.nacos.common.remote.client] [LoggerUtils.java:60] [trace=,span=,parent=] - [efaccc35-ff65-47c5-ab6b-ecdc60b1932d]Notify disconnected event to listeners
2022-05-23 18:16:57,455 [com.alibaba.nacos.client.remote.worker] INFO  [com.alibaba.nacos.common.remote.client] [LoggerUtils.java:60] [trace=,span=,parent=] - [e3148ab7-3a66-42db-bd7e-8b515f1250b4_config-0]Notify disconnected event to listeners
2022-05-23 18:16:57,455 [com.alibaba.nacos.client.remote.worker] WARN  [com.alibaba.nacos.client.naming] [NamingGrpcRedoService.java:82] [trace=,span=,parent=] - Grpc connection disconnect, mark to redo
2022-05-23 18:16:57,455 [com.alibaba.nacos.client.remote.worker] INFO  [com.alibaba.nacos.client.config.impl.ClientWorker] [ClientWorker.java:688] [trace=,span=,parent=] - [e3148ab7-3a66-42db-bd7e-8b515f1250b4_config-0] DisConnected,clear listen context...
2022-05-23 18:16:57,455 [com.alibaba.nacos.client.remote.worker] INFO  [com.alibaba.nacos.common.remote.client] [LoggerUtils.java:60] [trace=,span=,parent=] - [e3148ab7-3a66-42db-bd7e-8b515f1250b4_config-0]Notify connected event to listeners.
2022-05-23 18:16:57,455 [com.alibaba.nacos.client.remote.worker] INFO  [com.alibaba.nacos.client.config.impl.ClientWorker] [ClientWorker.java:681] [trace=,span=,parent=] - [e3148ab7-3a66-42db-bd7e-8b515f1250b4_config-0] Connected,notify listen context...
2022-05-23 18:16:57,456 [com.alibaba.nacos.client.remote.worker] WARN  [com.alibaba.nacos.client.naming] [NamingGrpcRedoService.java:89] [trace=,span=,parent=] - mark to redo completed
2022-05-23 18:16:57,456 [com.alibaba.nacos.client.remote.worker] INFO  [com.alibaba.nacos.common.remote.client] [LoggerUtils.java:60] [trace=,span=,parent=] - [efaccc35-ff65-47c5-ab6b-ecdc60b1932d]Notify connected event to listeners.
2022-05-23 18:16:57,456 [com.alibaba.nacos.client.remote.worker] INFO  [com.alibaba.nacos.client.naming] [NamingGrpcRedoService.java:76] [trace=,span=,parent=] - Grpc connection connect
2022-05-23 18:16:57,502 [com.alibaba.nacos.client.naming.updater.2] ERROR [com.alibaba.nacos.common.remote.client] [LoggerUtils.java:99] [trace=,span=,parent=] - Send request fail, request=ServiceQueryRequest{headers={}, requestId='null'}, retryTimes=2,errorMessage=Client not connected,current status:UNHEALTHY
2022-05-23 18:16:57,502 [com.alibaba.nacos.client.Worker] ERROR [com.alibaba.nacos.common.remote.client] [LoggerUtils.java:99] [trace=,span=,parent=] - Send request fail, request=ConfigBatchListenRequest{headers={}, requestId='null'}, retryTimes=2,errorMessage=Client not connected,current status:UNHEALTHY
2022-05-23 18:16:57,503 [com.alibaba.nacos.client.Worker] ERROR [com.alibaba.nacos.client.config.impl.ClientWorker] [ClientWorker.java:878] [trace=,span=,parent=] - Async listen config change error 
com.alibaba.nacos.api.exception.NacosException: Client not connected,current status:UNHEALTHY
	at com.alibaba.nacos.common.remote.client.RpcClient.request(RpcClient.java:655)
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.requestProxy(ClientWorker.java:1067)
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.requestProxy(ClientWorker.java:1042)
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.executeConfigListen(ClientWorker.java:831)
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient$4.run(ClientWorker.java:748)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2022-05-23 18:16:57,503 [com.alibaba.nacos.client.naming.updater.2] WARN  [com.alibaba.nacos.client.naming] [ServiceInfoUpdateService.java:195] [trace=,span=,parent=] - [NA] failed to update serviceName: DEFAULT_GROUP@@xm-auth
com.alibaba.nacos.api.exception.NacosException: Request nacos server failed: 
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:279)
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.queryInstancesOfService(NamingGrpcClientProxy.java:169)
	at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.queryInstancesOfService(NamingClientProxyDelegate.java:111)
	at com.alibaba.nacos.client.naming.core.ServiceInfoUpdateService$UpdateTask.run(ServiceInfoUpdateService.java:182)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.alibaba.nacos.api.exception.NacosException: Client not connected,current status:UNHEALTHY
	at com.alibaba.nacos.common.remote.client.RpcClient.request(RpcClient.java:655)
	at com.alibaba.nacos.common.remote.client.RpcClient.request(RpcClient.java:635)
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:269)
	... 10 common frames omitted
2022-05-23 18:16:57,565 [com.alibaba.nacos.client.remote.worker] INFO  [com.alibaba.nacos.common.remote.client] [LoggerUtils.java:60] [trace=,span=,parent=] - [e3148ab7-3a66-42db-bd7e-8b515f1250b4_config-0] success to connect a server  [172.18.87.174:8848],connectionId=1653301017461_172.18.86.63_51992
2022-05-23 18:16:57,565 [com.alibaba.nacos.client.remote.worker] INFO  [com.alibaba.nacos.common.remote.client] [LoggerUtils.java:60] [trace=,span=,parent=] - [e3148ab7-3a66-42db-bd7e-8b515f1250b4_config-0] Abandon prev connection ,server is  172.18.87.174:8848, connectionId is 1653301017320_172.18.86.63_51988
2022-05-23 18:16:57,572 [com.alibaba.nacos.client.remote.worker] INFO  [com.alibaba.nacos.common.remote.client] [LoggerUtils.java:60] [trace=,span=,parent=] - [efaccc35-ff65-47c5-ab6b-ecdc60b1932d] success to connect a server  [119.23.204.229:8848],connectionId=1653301017465_119.23.204.229_41696
2022-05-23 18:16:57,572 [com.alibaba.nacos.client.remote.worker] INFO  [com.alibaba.nacos.common.remote.client] [LoggerUtils.java:60] [trace=,span=,parent=] - [efaccc35-ff65-47c5-ab6b-ecdc60b1932d] Abandon prev connection ,server is  119.23.204.229:8848, connectionId is 1653301017331_119.23.204.229_41692
2022-05-23 18:16:57,572 [nacos-grpc-client-executor-1992] INFO  [com.alibaba.nacos.common.remote.client.grpc.GrpcClient] [LoggerUtils.java:60] [trace=,span=,parent=] - [1653301017320_172.18.86.63_51988]Ignore complete event,isRunning:false,isAbandon=true
2022-05-23 18:16:57,574 [com.alibaba.nacos.client.remote.worker] INFO  [com.alibaba.nacos.common.remote.client] [LoggerUtils.java:60] [trace=,span=,parent=] - [e3148ab7-3a66-42db-bd7e-8b515f1250b4_config-0]Notify disconnected event to listeners
2022-05-23 18:16:57,574 [com.alibaba.nacos.client.remote.worker] INFO  [com.alibaba.nacos.client.config.impl.ClientWorker] [ClientWorker.java:688] [trace=,span=,parent=] - [e3148ab7-3a66-42db-bd7e-8b515f1250b4_config-0] DisConnected,clear listen context...
2022-05-23 18:16:57,575 [com.alibaba.nacos.client.remote.worker] INFO  [com.alibaba.nacos.common.remote.client] [LoggerUtils.java:60] [trace=,span=,parent=] - [efaccc35-ff65-47c5-ab6b-ecdc60b1932d]Notify disconnected event to listeners
2022-05-23 18:16:57,576 [com.alibaba.nacos.client.remote.worker] INFO  [com.alibaba.nacos.common.remote.client] [LoggerUtils.java:60] [trace=,span=,parent=] - [e3148ab7-3a66-42db-bd7e-8b515f1250b4_config-0]Notify connected event to listeners.
2022-05-23 18:16:57,576 [com.alibaba.nacos.client.remote.worker] WARN  [com.alibaba.nacos.client.naming] [NamingGrpcRedoService.java:82] [trace=,span=,parent=] - Grpc connection disconnect, mark to redo
2022-05-23 18:16:57,576 [com.alibaba.nacos.client.remote.worker] INFO  [com.alibaba.nacos.client.config.impl.ClientWorker] [ClientWorker.java:681] [trace=,span=,parent=] - [e3148ab7-3a66-42db-bd7e-8b515f1250b4_config-0] Connected,notify listen context...
2022-05-23 18:16:57,576 [com.alibaba.nacos.client.remote.worker] WARN  [com.alibaba.nacos.client.naming] [NamingGrpcRedoService.java:89] [trace=,span=,parent=] - mark to redo completed
2022-05-23 18:16:57,576 [com.alibaba.nacos.client.remote.worker] INFO  [com.alibaba.nacos.common.remote.client] [LoggerUtils.java:60] [trace=,span=,parent=] - [efaccc35-ff65-47c5-ab6b-ecdc60b1932d]Notify connected event to listeners.
2022-05-23 18:16:57,576 [com.alibaba.nacos.client.remote.worker] INFO  [com.alibaba.nacos.client.naming] [NamingGrpcRedoService.java:76] [trace=,span=,parent=] - Grpc connection connect
2022-05-23 18:16:57,578 [com.alibaba.nacos.client.remote.worker] INFO  [com.alibaba.nacos.common.remote.client] [LoggerUtils.java:60] [trace=,span=,parent=] - [e3148ab7-3a66-42db-bd7e-8b515f1250b4_config-0] Server check success,currentServer is172.18.87.174:8848 
2022-05-23 18:16:57,578 [nacos-grpc-client-executor-2038] WARN  [com.alibaba.nacos.common.remote.client.grpc.GrpcClient] [LoggerUtils.java:86] [trace=,span=,parent=] - [1653301017331_119.23.204.229_41692]Ignore error event,isRunning:true,isAbandon=true
2022-05-23 18:16:57,579 [com.alibaba.nacos.client.remote.worker] INFO  [com.alibaba.nacos.common.remote.client] [LoggerUtils.java:60] [trace=,span=,parent=] - [efaccc35-ff65-47c5-ab6b-ecdc60b1932d] Server check success,currentServer is119.23.204.229:8848 
2022-05-23 18:16:57,584 [SpringApplicationShutdownHook] INFO  [com.alibaba.cloud.nacos.registry.NacosServiceRegistry] [NacosServiceRegistry.java:90] [trace=,span=,parent=] - De-registering from Nacos Server now...
2022-05-23 18:16:57,585 [SpringApplicationShutdownHook] INFO  [com.alibaba.nacos.client.naming] [NamingGrpcClientProxy.java:136] [trace=,span=,parent=] - [DEREGISTER-SERVICE] public deregistering service xm-auth with instance: Instance{instanceId='null', ip='119.23.204.229', port=50100, weight=1.0, healthy=true, enabled=true, ephemeral=true, clusterName='DEFAULT', serviceName='null', metadata={}}
2022-05-23 18:16:57,591 [SpringApplicationShutdownHook] INFO  [com.alibaba.cloud.nacos.registry.NacosServiceRegistry] [NacosServiceRegistry.java:110] [trace=,span=,parent=] - De-registration finished.
2022-05-23 18:16:57,591 [SpringApplicationShutdownHook] INFO  [com.alibaba.nacos.client.naming] [ServiceInfoHolder.java:256] [trace=,span=,parent=] - com.alibaba.nacos.client.naming.cache.ServiceInfoHolder do shutdown begin
2022-05-23 18:16:57,592 [SpringApplicationShutdownHook] INFO  [com.alibaba.nacos.client.naming] [FailoverReactor.java:140] [trace=,span=,parent=] - com.alibaba.nacos.client.naming.backups.FailoverReactor do shutdown begin
2022-05-23 18:16:57,592 [SpringApplicationShutdownHook] INFO  [com.alibaba.nacos.client.naming] [FailoverReactor.java:142] [trace=,span=,parent=] - com.alibaba.nacos.client.naming.backups.FailoverReactor do shutdown stop
2022-05-23 18:16:57,592 [SpringApplicationShutdownHook] INFO  [com.alibaba.nacos.client.naming] [ServiceInfoHolder.java:258] [trace=,span=,parent=] - com.alibaba.nacos.client.naming.cache.ServiceInfoHolder do shutdown stop
2022-05-23 18:16:57,592 [SpringApplicationShutdownHook] INFO  [com.alibaba.nacos.client.naming] [NamingClientProxyDelegate.java:176] [trace=,span=,parent=] - com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate do shutdown begin
2022-05-23 18:16:57,592 [SpringApplicationShutdownHook] INFO  [com.alibaba.nacos.client.naming] [ServiceInfoUpdateService.java:130] [trace=,span=,parent=] - com.alibaba.nacos.client.naming.core.ServiceInfoUpdateService do shutdown begin
2022-05-23 18:16:57,654 [com.alibaba.nacos.client.Worker] ERROR [com.alibaba.nacos.common.remote.client] [LoggerUtils.java:99] [trace=,span=,parent=] - Send request fail, request=ConfigBatchListenRequest{headers={charset=UTF-8, Client-AppName=unknown, Client-RequestToken=e441f8d5da4afd248ab16ebed0c61849, Client-RequestTS=1653301017553, exConfigInfo=true, Timestamp=1653301017553}, requestId='null'}, retryTimes=0,errorMessage=Client not connected,current status:UNHEALTHY
2022-05-23 18:16:57,893 [SpringApplicationShutdownHook] INFO  [com.alibaba.nacos.client.naming] [ServiceInfoUpdateService.java:132] [trace=,span=,parent=] - com.alibaba.nacos.client.naming.core.ServiceInfoUpdateService do shutdown stop
2022-05-23 18:16:57,895 [SpringApplicationShutdownHook] INFO  [com.alibaba.nacos.client.naming] [ServerListManager.java:188] [trace=,span=,parent=] - com.alibaba.nacos.client.naming.core.ServerListManager do shutdown begin
2022-05-23 18:16:57,895 [SpringApplicationShutdownHook] WARN  [com.alibaba.nacos.client.naming] [NamingHttpClientManager.java:72] [trace=,span=,parent=] - [NamingHttpClientManager] Start destroying NacosRestTemplate
2022-05-23 18:16:57,895 [SpringApplicationShutdownHook] WARN  [com.alibaba.nacos.client.naming] [NamingHttpClientManager.java:79] [trace=,span=,parent=] - [NamingHttpClientManager] Destruction of the end
2022-05-23 18:16:57,895 [SpringApplicationShutdownHook] INFO  [com.alibaba.nacos.client.naming] [ServerListManager.java:193] [trace=,span=,parent=] - com.alibaba.nacos.client.naming.core.ServerListManager do shutdown stop
2022-05-23 18:16:57,895 [SpringApplicationShutdownHook] INFO  [com.alibaba.nacos.client.naming] [NamingHttpClientProxy.java:519] [trace=,span=,parent=] - com.alibaba.nacos.client.naming.remote.http.NamingHttpClientProxy do shutdown begin
2022-05-23 18:16:57,896 [SpringApplicationShutdownHook] INFO  [com.alibaba.nacos.client.naming] [BeatReactor.java:162] [trace=,span=,parent=] - com.alibaba.nacos.client.naming.beat.BeatReactor do shutdown begin
2022-05-23 18:16:57,896 [SpringApplicationShutdownHook] INFO  [com.alibaba.nacos.client.naming] [BeatReactor.java:164] [trace=,span=,parent=] - com.alibaba.nacos.client.naming.beat.BeatReactor do shutdown stop
2022-05-23 18:16:57,896 [SpringApplicationShutdownHook] WARN  [com.alibaba.nacos.client.naming] [NamingHttpClientManager.java:72] [trace=,span=,parent=] - [NamingHttpClientManager] Start destroying NacosRestTemplate
2022-05-23 18:16:57,896 [SpringApplicationShutdownHook] WARN  [com.alibaba.nacos.client.naming] [NamingHttpClientManager.java:79] [trace=,span=,parent=] - [NamingHttpClientManager] Destruction of the end
2022-05-23 18:16:57,896 [SpringApplicationShutdownHook] INFO  [com.alibaba.nacos.client.identify.CredentialWatcher] [CredentialWatcher.java:105] [trace=,span=,parent=] - [null] CredentialWatcher is stopped
2022-05-23 18:16:57,896 [SpringApplicationShutdownHook] INFO  [com.alibaba.nacos.client.identify.CredentialService] [CredentialService.java:99] [trace=,span=,parent=] - [null] CredentialService is freed
2022-05-23 18:16:57,896 [SpringApplicationShutdownHook] INFO  [com.alibaba.nacos.client.naming] [NamingHttpClientProxy.java:523] [trace=,span=,parent=] - com.alibaba.nacos.client.naming.remote.http.NamingHttpClientProxy do shutdown stop
2022-05-23 18:16:57,896 [SpringApplicationShutdownHook] INFO  [com.alibaba.nacos.common.remote.client] [RpcClient.java:461] [trace=,span=,parent=] - Shutdown rpc client ,set status to shutdown
2022-05-23 18:16:57,896 [SpringApplicationShutdownHook] INFO  [com.alibaba.nacos.common.remote.client] [RpcClient.java:463] [trace=,span=,parent=] - Shutdown  client event executor java.util.concurrent.ScheduledThreadPoolExecutor@77358f9a[Running, pool size = 2, active threads = 2, queued tasks = 0, completed tasks = 0]
2022-05-23 18:16:57,897 [SpringApplicationShutdownHook] INFO  [com.alibaba.nacos.common.remote.client] [RpcClient.java:465] [trace=,span=,parent=] - Close current connection 1653301017465_119.23.204.229_41696
2022-05-23 18:16:57,897 [SpringApplicationShutdownHook] INFO  [com.alibaba.nacos.common.remote.client.grpc.GrpcClient] [GrpcClient.java:83] [trace=,span=,parent=] - Shutdown grpc executor java.util.concurrent.ThreadPoolExecutor@1f2a6a64[Running, pool size = 17, active threads = 0, queued tasks = 0, completed tasks = 2043]
2022-05-23 18:16:57,897 [SpringApplicationShutdownHook] INFO  [com.alibaba.nacos.client.naming] [NamingGrpcRedoService.java:251] [trace=,span=,parent=] - Shutdown grpc redo service executor java.util.concurrent.ScheduledThreadPoolExecutor@3368a254[Running, pool size = 1, active threads = 0, queued tasks = 1, completed tasks = 2664]
2022-05-23 18:16:57,898 [SpringApplicationShutdownHook] INFO  [com.alibaba.nacos.client.naming] [NamingClientProxyDelegate.java:182] [trace=,span=,parent=] - com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate do shutdown stop
2022-05-23 18:16:57,899 [SpringApplicationShutdownHook] WARN  [org.springframework.beans.factory.support.DisposableBeanAdapter] [DisposableBeanAdapter.java:328] [trace=,span=,parent=] - Custom destroy method 'close' on bean with name 'nacosServiceRegistry' threw an exception: java.lang.NullPointerException
2022-05-23 18:16:58,062 [SpringApplicationShutdownHook] INFO  [com.baomidou.dynamic.datasource.DynamicRoutingDataSource] [DynamicRoutingDataSource.java:205] [trace=,span=,parent=] - dynamic-datasource start closing ....
2022-05-23 18:16:58,065 [SpringApplicationShutdownHook] INFO  [com.alibaba.druid.pool.DruidDataSource] [DruidDataSource.java:2073] [trace=,span=,parent=] - {dataSource-1} closing ...
2022-05-23 18:16:58,070 [SpringApplicationShutdownHook] INFO  [com.alibaba.druid.pool.DruidDataSource] [DruidDataSource.java:2146] [trace=,span=,parent=] - {dataSource-1} closed
2022-05-23 18:16:58,070 [SpringApplicationShutdownHook] INFO  [com.baomidou.dynamic.datasource.DynamicRoutingDataSource] [DynamicRoutingDataSource.java:209] [trace=,span=,parent=] - dynamic-datasource all closed success,bye

**Closed** 2024-04-17 03:23 UTC
Labels: area/Kubernetes, expired
