### ISSUE TITLE
nacos client /v1/auth/users/login error

### ISSUE THREAD

**Issue by steveoyung** [alibaba/nacos#4020] opened 2020-10-19 08:26 UTC
**evironment:**
nacos server: 1.3.2
nacos client: 1.3.2
springcloud alibaba 2.2.2-release

**description:**
      config:
        server-addr: @spring.application.cloud.nacos.config.server-addr@
        file-extension: yml
        refresh: true
        shared-dataids: @spring.application.cloud.nacos.config.shared-dataids@
        namespace: @spring.application.cloud.nacos.config.namespace@
        username: @spring.application.cloud.nacos.config.username@
        password: '@spring.application.cloud.nacos.config.password@'
      discovery:
        server-addr: @spring.application.cloud.nacos.discovery.server-addr@
        namespace: @spring.application.cloud.nacos.discovery.namespace@
        username: @spring.application.cloud.nacos.discovery.username@
        password: '@spring.application.cloud.nacos.discovery.password@'

**I got the error:** 
SecurityProxy:  v1/auth/users/login, params: {username=nacos}, bodyMap: {password=2333232322}, errorMsg: errCode: 100, errMsg: Nacos serialize for class [com.alibaba.nacos.common.http.HttpRestResult] failed.

**config service  incorrect.**
it works ok when delete blocks username/password。

**discovery service works ok**

**Comment by steveoyung** [comment] 2020-10-19 08:59
maybe There will be a bug.

**Comment by steveoyung** [comment] 2020-10-19 09:13
If password contains characters like @ etc, [ bodyMap.put("password", URLEncoder.encode(this.password, "utf-8")); ] makes password error,  so just remove characters like @。

**Comment by KomachiSion** [comment] 2020-10-19 09:19
will be fixed in 1.4.0

duplicate with #3992

**Comment by KomachiSion** [comment] 2020-10-19 09:25
@steveoyung I find your error seems is serialization error , can you provide full error information?

**Comment by steveoyung** [comment] 2020-10-19 12:16
> @steveoyung I find your error seems is serialization error , can you provide full error information?

@KomachiSion that's all error log.  I found the root cause:  password contains character '@', it does not match with the server api when urlencoding password (URLEncoder.encode(this.password, "utf-8"))

**Comment by KomachiSion** [comment] 2020-10-20 01:19
I know the caused reason and will be fixed in 1.4.0, detail see #3992 .

But when I test, the error is unknown user, not is serialization error.

So I want to know the response or what cause the serialization error.

Can you debug and get the response and provide in comment? Thanks

**Comment by KomachiSion** [comment] 2020-10-23 02:40
Serialization error will be fixed in 1.4.0, #3721

**Closed by KomachiSion** 2020-10-23 02:40 UTC
Labels: status/duplicate
