### ISSUE TITLE
Change the README.md file, adding the e-book link.

### ISSUE THREAD

**Issue by realJackSun** [alibaba/nacos#7459] opened 2021-12-20 06:18 UTC

**Comment by sguzowski86** [comment] 2022-01-02 07:23
https://github.com/realJackSun/nacos/commit/7d1ca3b05ef618496eb20d84edf95c43191a6992
Here is a link to the realJackSun / nacos website

**Comment by naniyerragangu99** [comment] 2022-01-10 04:01
iam already running code

**Comment by keubb** [comment] 2022-01-11 16:34
oi

**Comment by Ellendumpa** [comment] 2022-01-12 01:46
7459

**Comment by Ellendumpa** [comment] 2022-01-12 02:35
عاوزه ارجع جميل

**Comment by Ellendumpa** [comment] 2022-01-12 02:36
حد يساعدني

**Comment by kanwalbou** [comment] 2022-01-12 23:34
Jaazcash

**Comment by Maricruzhdz** [comment] 2022-01-16 14:45
Qqq

**Comment by Dyzinto** [comment] 2022-02-05 14:47
> _No description provided._

README.md

**Comment by Dyzinto** [comment] 2022-02-05 14:47
] Change the README.md file, adding the e-book link.

**Comment by Anacarladossantos** [comment] 2022-02-05 17:07
Vamos altera  o arquivo ReADME.md,e adicionando o link do e-book

**Comment by Kay-Ceee** [comment] 2022-02-20 21:41
Please follow me I have a lot instored 🥺🦋🤧

**Comment by Mikecarbon** [comment] 2022-03-17 13:58
Config\READ.e-book.md

**Comment by halid55** [comment] 2022-03-25 16:27
I started my project

**Comment by Adnanfir14** [comment] 2022-03-27 18:16
#7459

**Comment by Adnanfir14** [comment] 2022-03-27 18:16
#7459

**Comment by Dariinkaa** [comment] 2022-04-09 08:39
#7669 
Duplicate of #

**Comment by labareda09** [comment] 2022-07-29 11:01
opaa

**Comment by rookie-ricardo** [comment] 2022-09-02 08:36
@i will solve it@

**Comment by rookie-ricardo** [comment] 2022-09-06 01:59
“https://github.com/ready to close@”

**Closed** 2022-09-22 06:08 UTC
Labels: good first issue
