### ISSUE TITLE
nacos服务端升级到1.3.1一直打印error日志

### ISSUE THREAD

**Issue by mumuyuanbao** [alibaba/nacos#3458] opened 2020-07-28 08:21 UTC
nacos-server升级到1.3.1 
client也升级到1.3.1
配置的集群连接之后，一直打印 error日志
服务已经注册上了，并且能够正常调用
2020-07-28 16:09:58.406 ERROR [shop-order-application,,,] 1 --- [.naming.updater] com.alibaba.nacos.client.naming          : [NA] failed to request
java.net.UnknownHostException: ﻿ip
	at java.net.InetAddress.getAllByName0(Unknown Source)
	at java.net.InetAddress.getAllByName(Unknown Source)
	at java.net.InetAddress.getAllByName(Unknown Source)
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at com.alibaba.nacos.common.http.client.DefaultHttpClientRequest.execute(DefaultHttpClientRequest.java:54)
	at com.alibaba.nacos.common.http.client.NacosRestTemplate.execute(NacosRestTemplate.java:330)
	at com.alibaba.nacos.common.http.client.NacosRestTemplate.exchangeForm(NacosRestTemplate.java:319)
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:599)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:524)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:491)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:486)
	at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:400)
	at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:330)
	at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:397)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by mumuyuanbao** [comment] 2020-07-28 08:31
次次都是日志惹的祸，毛病

**Comment by KomachiSion** [comment] 2020-07-28 12:46
I will be fixed in 1.3.2, please rollback client to 1.3.0 use first.

**Comment by KomachiSion** [comment] 2020-07-28 12:49
BTW， the error information is unknown host, which means the host may be some problem.

**Comment by KomachiSion** [comment] 2020-08-03 07:35
After researching, It is caused by the spring-cloud covers nacos‘ log configuration, so that these log which should be printed to `naming.log` print to users log.

And it's hard to fix perfectly, because log(logback and log4j) context is static.

**Comment by mumuyuanbao** [comment] 2020-08-04 02:02
在远程调用或发现服务时失败，造成的日志打印。配置的服务地址Nacos不能清楚识别，是否考虑加入打印错误日志时，将无法连接的地址与服务通过日志显示。好排查服务问题

**Comment by KomachiSion** [comment] 2020-08-27 01:37
问题还是分开吧，日志打印问题确实有，原因是sc会覆盖nacos-client的日志配置，导致本来该打在nacos日志文件的日志打印到业务日志里。
关于报错内容，显然就是自己环境的问题了，unknown host肯定是域名解析有问题。

**Closed by KomachiSion** 2020-08-27 01:37 UTC
Labels: status/invalid
